config/routes.rb
Rails.application.routes.draw do
  resources :alphas
  root 'pages#Home'

  get 'about' => 'pages#About'

  get 'contact' => 'pages#Contact'

  get 'how' => 'pages#How'

  devise_for :users

end

app/models/alpha.rb
class Alpha < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/alphas_controller.rb
class AlphasController < ApplicationController
  before_action :set_alpha, only: [:show, :edit, :update, :destroy]

  # GET /alphas
  # GET /alphas.json
  def index
    @alphas = Alpha.all
  end

  # GET /alphas/1
  # GET /alphas/1.json
  def show
  end

  # GET /alphas/new
  def new
    @alpha = Alpha.new
  end

  # GET /alphas/1/edit
  def edit
  end

  # POST /alphas
  # POST /alphas.json
  def create
    @alpha = Alpha.new(alpha_params)

    respond_to do |format|
      if @alpha.save
        format.html { redirect_to @alpha, notice: 'Alpha was successfully created.' }
        format.json { render :show, status: :created, location: @alpha }
      else
        format.html { render :new }
        format.json { render json: @alpha.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alphas/1
  # PATCH/PUT /alphas/1.json
  def update
    respond_to do |format|
      if @alpha.update(alpha_params)
        format.html { redirect_to @alpha, notice: 'Alpha was successfully updated.' }
        format.json { render :show, status: :ok, location: @alpha }
      else
        format.html { render :edit }
        format.json { render json: @alpha.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alphas/1
  # DELETE /alphas/1.json
  def destroy
    @alpha.destroy
    respond_to do |format|
      format.html { redirect_to alphas_url, notice: 'Alpha was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alpha
      @alpha = Alpha.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alpha_params
      params.require(:alpha).permit(:name, :email, :degree, :college)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def Home
 	@alpha = Alpha.new
  end

  def About
  end

  def Contact
  end

  def How
  end
end

app/helpers/alphas_helper.rb
module AlphasHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/alphas/_form.html.erb
<%= form_for(@alpha) do |f| %>
  <% if @alpha.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@alpha.errors.count, "error") %> prohibited this alpha from being saved:</h2>

      <ul>
      <% @alpha.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :degree %><br>
    <%= f.text_field :degree %>
  </div>
  <div class="field">
    <%= f.label :college %><br>
    <%= f.text_field :college %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/alphas/edit.html.erb
<h1>Editing Alpha</h1>

<%= render 'form' %>

<%= link_to 'Show', @alpha %> |
<%= link_to 'Back', alphas_path %>

app/views/alphas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Alphas</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Degree</th>
      <th>College</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alphas.each do |alpha| %>
      <tr>
        <td><%= alpha.name %></td>
        <td><%= alpha.email %></td>
        <td><%= alpha.degree %></td>
        <td><%= alpha.college %></td>
        <td><%= link_to 'Show', alpha %></td>
        <td><%= link_to 'Edit', edit_alpha_path(alpha) %></td>
        <td><%= link_to 'Destroy', alpha, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Alpha', new_alpha_path %>

app/views/alphas/new.html.erb
<h1>New Alpha</h1>

<%= render 'form' %>

<%= link_to 'Back', alphas_path %>

app/views/alphas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @alpha.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @alpha.email %>
</p>

<p>
  <strong>Degree:</strong>
  <%= @alpha.degree %>
</p>

<p>
  <strong>College:</strong>
  <%= @alpha.college %>
</p>

<%= link_to 'Edit', edit_alpha_path(@alpha) %> |
<%= link_to 'Back', alphas_path %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#"><%=image_tag("logo.png") %></a>
             <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-sm btn-primary">Search</button>
      </form>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Investee<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Get Started</a></li>
            <li><a href="#">Students</a></li>
            <li><a href="#">Businesses</a></li>
          </ul>        
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Investor<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Get Started</a></li>
            <li><a href="#">Individual Accounts</a></li>
            <li><a href="#">Institutional Accounts</a></li>
          </ul>        
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">About<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">How It Works</a></li>
            <li><a href="#">Team / Advisory</a></li>
            <li><a href="#">Blog</a></li>
            <li><a href="#">Contact</a></li>
          </ul>        
        </li>

          <li><a href="#">Login</a></li>

      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Aq</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body style='background:#F5F8FA'>
<%= render 'layouts/navbar' %>
   <span class="notice"><%= notice %></span>
   <span class="alert"><%= alert %></span>

<div class='container' >
	<%= yield %>
</div>

</body>
</html>

app/views/pages/About.html.erb
<h1>Pages#About</h1>
<p>Find me in app/views/pages/About.html.erb</p>

app/views/pages/Contact.html.erb
<h1>Pages#Contact</h1>
<p>Find me in app/views/pages/Contact.html.erb</p>

app/views/pages/Home.html.erb
<div class="row">

  <div class="col-xs-3">
	  	<div class="panel panel-default" border='none'>

		  <div class='panel panel-body'>
		  <strong>Filters</strong><br><br>
			<form action="demo_form.asp">
			  <input type="checkbox" name="vehicle" value="Bike">Student Loans<br>
			  <input type="checkbox" name="vehicle" value="Car" checked>Business Loans<br>
			  <input type="checkbox" name="vehicle" value="Car" checked>AQ Scores<br>
			  <input type="checkbox" name="vehicle" value="Car" checked>Universities<br>
			  <br>
			  <input type="checkbox" name="vehicle" value="Bike">Latest<br>
			  <input type="checkbox" name="vehicle" value="Bike">Oldest<br>
			  <input type="checkbox" name="vehicle" value="Bike">Descending<br>
			  <input type="checkbox" name="vehicle" value="Bike">Ascending<br>
			<br><button type="submit" class="btn btn-sm btn-primary">Search</button>
			</form>
		  </div>
   	 	</div>
  </div>

  <div class="col-xs-6">
	  	<div class="panel panel-default">
		  <div class="panel-body">
		  <strong></strong>
		  </div>
   	 	</div>
  </div>

  <div class="col-xs-3">
	  	<div class="panel panel-default">
		  <div class="panel-body"><strong>Trending</strong><br><br>
		  <strong>#TopAQScores</strong>
		  	<ul>
		  		<li>985.0</li>
		  		<li>970.0</li>
		  		<li>958.33</li>
		  	</ul>
		  <strong>#TopDegrees</strong>
		  	<ul>
		  		<li>BS - Harvard University</li>
		  		<li>MBA - Cornell University</li>
		  		<li>MD - UNC</li>
		  	</ul>

		  <strong>#LargestInvestments</strong>
		  	<ul>
		  		<li>$1,500,000</li>
		  		<li>$750,000</li>
		  		<li>$550,000</li>
		  	</ul>

		  </div>
   	 	</div>
  </div>

</div>

<div class="row">
  <div class="col-xs-3">
	  	<div class="panel panel-default" border='none'>
		  <div class='panel panel-body'>
		  <strong>How much do you need?</strong><br><br>
		  <form>
			  Amount ($)<br>
			  <input type="text" name="firstname">
			  <br>
			  Student or Business<br>
			  <input type="text" name="lastname">
			  <br>
			  AQ Score<br>
			  <input type="text" name="firstname">
			  <br><br><button type="submit" class="btn btn-sm btn-primary">Check Plans</button>
		  </form>
		  </div>
   	 	</div>
  </div>


</div>

<div class="row">
  <div class="col-xs-3">
	  	<div class="panel panel-default" border='none'>
		  <div class='panel panel-body'>
		  <strong>Discover your AQ Score</strong><br><br>
		  <form>
			  First name:<br>
			  <input type="text" name="firstname" plac>
			  <br>
			  Last name:<br>
			  <input type="text" name="lastname">
			  <br>
			  College:<br>
			  <input type="text" name="firstname">
			  <br>
			  Degree<br>
			  <input type="text" name="lastname">
			  <br><br><button type="submit" class="btn btn-sm btn-primary">Get AQ</button>
		  </form>
		  </div>
   	 	</div>
  </div>

app/views/pages/How.html.erb
<h1>Pages#How</h1>
<p>Find me in app/views/pages/How.html.erb</p>